### PR TITLE
FR translation + ESOPE improvements

### PR DESCRIPTION
**Pull request by Facyla**
Hi,

I've updated your nice plugin with some changes that better fit our needs, here are the changes details : 
- languages/en.php : only spacing +  new string
- languages/fr.php : added
- views/default/plugins/rssimport/settings.php : added 2 settings 
  1. Imported element container setting : defaults to the container, instead of the owner, so to the group in a group, and the user when used outside of a group
  2. Enable per-tool import setting : gives a finer control over import availability
     Also there was another option (in a previous backport to 1.6) that let the tool be restricted to user/admins and also groupadmin - which is not enabled in this PR (as there is already a user/admin setting)
- lib/functions.php : new functions that implement the added settings, and also adds a filtering function based on imported domain name + real source URL detection. And also use a translation string for date.

If you are interested into these changes, we can discuss it further so i can update it until it's OK for you to merge ?
I could make a few more changes such as changing the defaults so it better integrates with existing instances, implement the group admin setting (which i think gives much more flexibility for big networks), and add a hook in the filtering function so it becomes more extendable...

Please let me know if you are interested.

Best regards,
Florian DANIEL

### CODE REVIEW

**Comment by beck24** [comment]
Sorry this is really late, I didn't notice this PR had been submitted.  I'm just about to upgrade this to 1.9 so will do so with this functionality.
A very delayed thanks! :)

**Comment by beck24** [comment]
Your implementation is buggy, you've been setting the **owner** guid as the group, instead of the **container**, I'll be changing that back for the 1.9 release

**Comment by Facyla** [comment]
Hi Matt,

Thanks for your return.

That behaviour is controlled by a plugin setting, and is actually what i wanted to have : when importing content, the owner can be set to the container, so when it's personnal the user gets the ownership, but when a group is configured to import content from eg. a blog or a Diigo group stream (which is one of my main use case), the ownership gets to the group itself.
Anyway this is only an option (or at least i hope it is in that version).

My latest version for Elgg 1.8 is at https://github.com/Facyla/esope/tree/master/mod/rssimport

Yours,
Florian

**Comment by beck24** [comment]
ok, sorry that's not going to work for this - groups don't own content in any other context, that's going against the general design patterns.

You can use any of these new hooks to hijack the import and do any site specific customizations:
https://github.com/AU-Landing-Project/rssimport/blob/master/classes/AU/RSSImport/RSSImport.php#L200

https://github.com/AU-Landing-Project/rssimport/blob/master/classes/AU/RSSImport/RSSImport.php#L409

https://github.com/AU-Landing-Project/rssimport/blob/master/classes/AU/RSSImport/RSSImport.php#L470

https://github.com/AU-Landing-Project/rssimport/blob/master/classes/AU/RSSImport/RSSImport.php#L540

**Comment by Facyla** [comment]
Ok, no problem ; now with the hooks it should be easy to add content filtering and change ownership without modifying the plugin itself :)

**Pull request merged**
